In [2]:
import sys
from pathlib import Path
import os
# sys.path.append(str(Path(os.getcwd()).parent.absolute()))
os.chdir(str(Path(os.getcwd()).parent.absolute()))
import pandas as pd
import numpy as np
import glob
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
df_test=pd.read_csv('data/test.csv')
df_train=pd.read_csv('data/train.csv')
df_census=pd.read_csv('data/census_starter.csv')
df_pop=pd.read_csv('data/population0410_07_19.csv')

In [4]:
df_train

,row_id,cfips,county,state,first_day_of_month,microbusiness_density,active
0,1001_2019-08-01,1001,Autauga County,Alabama,2019-08-01,3.007682,1249
1,1001_2019-09-01,1001,Autauga County,Alabama,2019-09-01,2.884870,1198
2,1001_2019-10-01,1001,Autauga County,Alabama,2019-10-01,3.055843,1269
3,1001_2019-11-01,1001,Autauga County,Alabama,2019-11-01,2.993233,1243
4,1001_2019-12-01,1001,Autauga County,Alabama,2019-12-01,2.993233,1243
...,...,...,...,...,...,...,...
122260,56045_2022-06-01,56045,Weston County,Wyoming,2022-06-01,1.803249,101
122261,56045_2022-07-01,56045,Weston County,Wyoming,2022-07-01,1.803249,101
122262,56045_2022-08-01,56045,Weston County,Wyoming,2022-08-01,1.785395,100
122263,56045_2022-09-01,56045,Weston County,Wyoming,2022-09-01,1.785395,100
122264,56045_2022-10-01,56045,Weston County,Wyoming,2022-10-01,1.785395,100

In [5]:
from src.utils import join

In [6]:
df_pop=df_pop.assign(county=lambda x:x['Geographic Area Name (Grouping)'].apply(lambda x:x.split(',')[0].strip()))\
    .assign(state=lambda x:x['Geographic Area Name (Grouping)'].apply(lambda x:x.split(',')[1].strip()))\
    .drop(['Geographic Area Name (Grouping)'],axis=1)

In [7]:
df_pop

,4/1/2010 Census population!!Population,4/1/2010 population estimates base!!Population,7/1/2010 population estimate!!Population,7/1/2011 population estimate!!Population,7/1/2012 population estimate!!Population,7/1/2013 population estimate!!Population,7/1/2014 population estimate!!Population,7/1/2015 population estimate!!Population,7/1/2016 population estimate!!Population,7/1/2017 population estimate!!Population,7/1/2018 population estimate!!Population,7/1/2019 population estimate!!Population,county,state
0,"54,571","54,597","54,773","55,227","54,954","54,727","54,893","54,864","55,243","55,390","55,533","55,869",Autauga County,Alabama
1,"182,265","182,265","183,112","186,558","190,145","194,885","199,183","202,939","207,601","212,521","217,855","223,234",Baldwin County,Alabama
2,"27,457","27,455","27,327","27,341","27,169","26,937","26,755","26,283","25,806","25,157","24,872","24,686",Barbour County,Alabama
3,"22,915","22,915","22,870","22,745","22,667","22,521","22,553","22,566","22,586","22,550","22,367","22,394",Bibb County,Alabama
4,"57,322","57,322","57,376","57,560","57,580","57,619","57,526","57,526","57,494","57,787","57,771","57,826",Blount County,Alabama
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3215,"59,662","59,662","59,562","58,688","57,857","57,063","55,942","54,805","53,677","52,318","50,136","50,023",Vega Baja Municipio,Puerto Rico
3216,"9,301","9,301","9,314","9,247","9,227","9,179","9,081","8,965","8,833","8,666","8,362","8,386",Vieques Municipio,Puerto Rico
3217,"26,073","26,073","26,001","25,542","25,135","24,745","24,256","23,662","23,091","22,452","21,436","21,372",Villalba Municipio,Puerto Rico
3218,"37,941","37,941","37,874","37,361","36,844","36,377","35,732","35,076","34,363","33,519","32,254","32,282",Yabucoa Municipio,Puerto Rico
3219,"42,043","41,947","41,828","41,036","40,249","39,492","38,535","37,585","36,654","35,474","33,853","33,575",Yauco Municipio,Puerto Rico

In [8]:
df_train

,row_id,cfips,county,state,first_day_of_month,microbusiness_density,active
0,1001_2019-08-01,1001,Autauga County,Alabama,2019-08-01,3.007682,1249
1,1001_2019-09-01,1001,Autauga County,Alabama,2019-09-01,2.884870,1198
2,1001_2019-10-01,1001,Autauga County,Alabama,2019-10-01,3.055843,1269
3,1001_2019-11-01,1001,Autauga County,Alabama,2019-11-01,2.993233,1243
4,1001_2019-12-01,1001,Autauga County,Alabama,2019-12-01,2.993233,1243
...,...,...,...,...,...,...,...
122260,56045_2022-06-01,56045,Weston County,Wyoming,2022-06-01,1.803249,101
122261,56045_2022-07-01,56045,Weston County,Wyoming,2022-07-01,1.803249,101
122262,56045_2022-08-01,56045,Weston County,Wyoming,2022-08-01,1.785395,100
122263,56045_2022-09-01,56045,Weston County,Wyoming,2022-09-01,1.785395,100
122264,56045_2022-10-01,56045,Weston County,Wyoming,2022-10-01,1.785395,100

In [9]:
df_test

                 row_id  cfips first_day_of_month
0       1001_2022-11-01   1001         2022-11-01
1       1003_2022-11-01   1003         2022-11-01
2       1005_2022-11-01   1005         2022-11-01
3       1007_2022-11-01   1007         2022-11-01
4       1009_2022-11-01   1009         2022-11-01
...                 ...    ...                ...
25075  56037_2023-06-01  56037         2023-06-01
25076  56039_2023-06-01  56039         2023-06-01
25077  56041_2023-06-01  56041         2023-06-01
25078  56043_2023-06-01  56043         2023-06-01
25079  56045_2023-06-01  56045         2023-06-01

[25080 rows x 3 columns]

In [10]:
df_cfips=df_train[['cfips','county','state']].drop_duplicates()

In [11]:
df_train=join(df_train,df_pop,on=['county','state'],how='left')
df_train=join(df_train,df_census,on=['cfips'],how='left')

df_test=join(df_test,df_cfips,on=['cfips'],how='inner')
df_test=join(df_test,df_pop,on=['county','state'],how='left')
df_test=join(df_test,df_census,on=['cfips'],how='left')

In [12]:
df_test.columns.__len__()

42

In [13]:
df_train.columns.__len__()

44

In [24]:
df_train.head()

,row_id,cfips,county,state,first_day_of_month,microbusiness_density,active,4/1/2010 Census population!!Population,4/1/2010 population estimates base!!Population,7/1/2010 population estimate!!Population,...,pct_it_workers_2017,pct_it_workers_2018,pct_it_workers_2019,pct_it_workers_2020,pct_it_workers_2021,median_hh_inc_2017,median_hh_inc_2018,median_hh_inc_2019,median_hh_inc_2020,median_hh_inc_2021
0,1001_2019-08-01,1001,Autauga County,Alabama,2019-08-01,3.007682,1249,"54,571","54,597","54,773",...,1.3,1.1,0.7,0.6,1.1,55317,58786.0,58731,57982.0,62660.0
1,1001_2019-09-01,1001,Autauga County,Alabama,2019-09-01,2.884870,1198,"54,571","54,597","54,773",...,1.3,1.1,0.7,0.6,1.1,55317,58786.0,58731,57982.0,62660.0
2,1001_2019-10-01,1001,Autauga County,Alabama,2019-10-01,3.055843,1269,"54,571","54,597","54,773",...,1.3,1.1,0.7,0.6,1.1,55317,58786.0,58731,57982.0,62660.0
3,1001_2019-11-01,1001,Autauga County,Alabama,2019-11-01,2.993233,1243,"54,571","54,597","54,773",...,1.3,1.1,0.7,0.6,1.1,55317,58786.0,58731,57982.0,62660.0
4,1001_2019-12-01,1001,Autauga County,Alabama,2019-12-01,2.993233,1243,"54,571","54,597","54,773",...,1.3,1.1,0.7,0.6,1.1,55317,58786.0,58731,57982.0,62660.0

In [25]:
df_test

,row_id,cfips,first_day_of_month,county,state,4/1/2010 Census population!!Population,4/1/2010 population estimates base!!Population,7/1/2010 population estimate!!Population,7/1/2011 population estimate!!Population,7/1/2012 population estimate!!Population,...,pct_it_workers_2017,pct_it_workers_2018,pct_it_workers_2019,pct_it_workers_2020,pct_it_workers_2021,median_hh_inc_2017,median_hh_inc_2018,median_hh_inc_2019,median_hh_inc_2020,median_hh_inc_2021
0,1001_2022-11-01,1001,2022-11-01,Autauga County,Alabama,"54,571","54,597","54,773","55,227","54,954",...,1.3,1.1,0.7,0.6,1.1,55317,58786.0,58731,57982.0,62660.0
1,1001_2022-12-01,1001,2022-12-01,Autauga County,Alabama,"54,571","54,597","54,773","55,227","54,954",...,1.3,1.1,0.7,0.6,1.1,55317,58786.0,58731,57982.0,62660.0
2,1001_2023-01-01,1001,2023-01-01,Autauga County,Alabama,"54,571","54,597","54,773","55,227","54,954",...,1.3,1.1,0.7,0.6,1.1,55317,58786.0,58731,57982.0,62660.0
3,1001_2023-02-01,1001,2023-02-01,Autauga County,Alabama,"54,571","54,597","54,773","55,227","54,954",...,1.3,1.1,0.7,0.6,1.1,55317,58786.0,58731,57982.0,62660.0
4,1001_2023-03-01,1001,2023-03-01,Autauga County,Alabama,"54,571","54,597","54,773","55,227","54,954",...,1.3,1.1,0.7,0.6,1.1,55317,58786.0,58731,57982.0,62660.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25075,56045_2023-02-01,56045,2023-02-01,Weston County,Wyoming,"7,208","7,208","7,198","7,142","7,077",...,0.6,0.6,0.0,0.0,0.0,59605,52867.0,57031,53333.0,65566.0
25076,56045_2023-03-01,56045,2023-03-01,Weston County,Wyoming,"7,208","7,208","7,198","7,142","7,077",...,0.6,0.6,0.0,0.0,0.0,59605,52867.0,57031,53333.0,65566.0
25077,56045_2023-04-01,56045,2023-04-01,Weston County,Wyoming,"7,208","7,208","7,198","7,142","7,077",...,0.6,0.6,0.0,0.0,0.0,59605,52867.0,57031,53333.0,65566.0
25078,56045_2023-05-01,56045,2023-05-01,Weston County,Wyoming,"7,208","7,208","7,198","7,142","7,077",...,0.6,0.6,0.0,0.0,0.0,59605,52867.0,57031,53333.0,65566.0
25079,56045_2023-06-01,56045,2023-06-01,Weston County,Wyoming,"7,208","7,208","7,198","7,142","7,077",...,0.6,0.6,0.0,0.0,0.0,59605,52867.0,57031,53333.0,65566.0